package uz.pdp.anicinema.utils.enums;

import lombok.Getter;

@Getter
public enum Code {

    SUCCESS,
    UNAUTHORIZED,
    FORBIDDEN,
    DATA_NOT_ACTIVE,
    ACCESS_DENIED,
    IDENTIFICATION_REQUIRED,
    OTP_REQUIRED,
    INVALID_OTP_CODE,
    DATA_ALREADY_EXISTS,
    TOKEN_EXPIRED,
    DATA_NOT_FOUND,
    UNREGISTERED_DEVICE,
    INVALID_DATA,
    DATA_INCOMPLETE,
    BLOCKED_DEVICE,
    BLOCKED_USER,
    INSUFFICIENT_FUNDS,
    OPERATION_FAILED,
    OPERATION_PENDING,
    OPERATION_WAITING,
    UNAVAILABLE,
    CARD_IS_EMPTY,
    OPERATION_LIMIT_EXCEEDED,
    UNEXPECTED_ERROR

}
